# Generated by Django 3.2.4 on 2021-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='type',
        ),
    ]
